// Copyright Kani Contributors
// SPDX-License-Identifier: Apache-2.0 OR MIT

use anyhow::{Context, Result};
use std::ffi::{OsStr, OsString};
use std::fs;
use std::fs::File;
use std::io::BufReader;
use std::path::Path;
use std::process::Command;
#[cfg(windows)]
use std::time::{Duration, Instant};

use crate::metadata::collect_and_link_function_pointer_restrictions;
use crate::project::Project;
use crate::session::KaniSession;
use crate::util::alter_extension;
use kani_metadata::{ArtifactType, HarnessMetadata};

impl KaniSession {
    /// Instrument and optimize a goto binary in-place.
    pub fn instrument_model(
        &self,
        input: &Path,
        output: &Path,
        project: &Project,
        harness: &HarnessMetadata,
    ) -> Result<()> {
        // We actually start by calling goto-cc to start the specialization:
        self.specialize_to_proof_harness(input, output, &harness.mangled_name)?;

        let restrictions = project.get_harness_artifact(harness, ArtifactType::VTableRestriction);
        if let Some(restrictions_path) = restrictions {
            self.apply_vtable_restrictions(output, restrictions_path)?;
        }

        // Run sanity checks in the model generated by kani-compiler before any goto-instrument
        // transformation.
        if self.args.run_sanity_checks {
            self.goto_sanity_check(output)?;
        }

        let is_loop_contracts_enabled = self
            .args
            .common_args
            .unstable_features
            .contains(kani_metadata::UnstableFeature::LoopContracts)
            && harness.has_loop_contracts;
        self.instrument_contracts(harness, is_loop_contracts_enabled, output)?;

        if self.args.checks.undefined_function_on() {
            self.add_library(output)?;
            self.undefined_functions(output)?;
        } else {
            self.just_drop_unused_functions(output)?;
        }

        self.rewrite_back_edges(output)?;

        if self.args.gen_c {
            let c_outfile = alter_extension(output, "c");
            // We don't put the C file into temporaries to be deleted.

            self.gen_c(output, &c_outfile)?;

            if !self.args.common_args.quiet {
                println!("Generated C code written to {}", c_outfile.to_string_lossy());
            }

            let c_demangled = alter_extension(output, "demangled.c");
            let prett_name_map =
                project.get_harness_artifact(harness, ArtifactType::PrettyNameMap).unwrap();
            self.demangle_c(prett_name_map, &c_outfile, &c_demangled)?;
            if !self.args.common_args.quiet {
                println!("Demangled GotoC code written to {}", c_demangled.to_string_lossy())
            }
        }

        Ok(())
    }

    /// Apply -Z restrict-vtable to a goto binary.
    pub fn apply_vtable_restrictions(&self, goto_file: &Path, restrictions: &Path) -> Result<()> {
        let linked_restrictions = alter_extension(goto_file, "linked-restrictions.json");
        self.record_temporary_file(&linked_restrictions);
        collect_and_link_function_pointer_restrictions(restrictions, &linked_restrictions)?;

        let args: Vec<OsString> = vec![
            "--function-pointer-restrictions-file".into(),
            Self::normalize_tool_path(&linked_restrictions),
            Self::normalize_tool_path(goto_file), // input
            Self::normalize_tool_path(goto_file), // output
        ];

        self.call_goto_instrument(args)
    }

    /// Link the binary against the CBMC model for C library functions.
    /// Normally this happens implicitly, but we use this explicitly
    /// before we invoke `undefined_functions` below, otherwise these
    /// functions appear undefined.
    fn add_library(&self, file: &Path) -> Result<()> {
        let args: Vec<OsString> = vec![
            "--add-library".into(),
            "--no-malloc-may-fail".into(),
            Self::normalize_tool_path(file), // input
            Self::normalize_tool_path(file), // output
        ];

        self.call_goto_instrument(args)
    }

    /// Instruct CBMC to "assert false" when invoking an undefined function.
    /// (This contrasts with its default behavior of returning `nondet`, which is
    /// unsound in the face of side-effects.)
    /// Then remove unused functions. (Oddly, it seems CBMC will both see some
    /// functions as unused and remove them, and also as used and so would
    /// generate "assert false". So it's essential to do this afterwards.)
    fn undefined_functions(&self, file: &Path) -> Result<()> {
        let args: Vec<OsString> = vec![
            "--generate-function-body-options".into(),
            "assert-false-assume-false".into(),
            "--generate-function-body".into(),
            ".*".into(),
            "--drop-unused-functions".into(),
            Self::normalize_tool_path(file), // input
            Self::normalize_tool_path(file), // output
        ];

        #[cfg(windows)]
        {
            if let Err(err) =
                self.call_goto_instrument_with_windows_timeout(&args, "--generate-function-body")
            {
                if !is_windows_goto_instrument_timeout(&err) {
                    return Err(err);
                }
                if !self.args.common_args.quiet {
                    println!(
                        "Warning: Falling back to --drop-unused-functions on Windows after goto-instrument timeout in undefined function body generation"
                    );
                }
                let drop_args: Vec<OsString> = vec![
                    "--drop-unused-functions".into(),
                    Self::normalize_tool_path(file), // input
                    Self::normalize_tool_path(file), // output
                ];
                return self.call_goto_instrument_with_windows_timeout(
                    &drop_args,
                    "--drop-unused-functions",
                );
            }
            Ok(())
        }
        #[cfg(not(windows))]
        {
            self.call_goto_instrument(args)
        }
    }

    /// Remove all functions unreachable from the current proof harness.
    fn just_drop_unused_functions(&self, file: &Path) -> Result<()> {
        let args: Vec<OsString> = vec![
            "--drop-unused-functions".into(),
            Self::normalize_tool_path(file), // input
            Self::normalize_tool_path(file), // output
        ];

        self.call_goto_instrument(args)
    }

    fn rewrite_back_edges(&self, file: &Path) -> Result<()> {
        let args: Vec<OsString> = vec![
            "--ensure-one-backedge-per-target".into(),
            Self::normalize_tool_path(file), // input
            Self::normalize_tool_path(file), // output
        ];

        self.call_goto_instrument(args)
    }

    fn goto_sanity_check(&self, file: &Path) -> Result<()> {
        let args: Vec<OsString> = vec![
            "--validate-goto-model".into(),
            Self::normalize_tool_path(file), // input
            Self::normalize_tool_path(file), // output
        ];

        self.call_goto_instrument(args)
    }

    /// Generate a .c file from a goto binary (i.e. --gen-c)
    pub fn gen_c(&self, file: &Path, output_file: &Path) -> Result<()> {
        let args: Vec<OsString> = vec![
            "--dump-c".into(),
            Self::normalize_tool_path(file),
            Self::normalize_tool_path(output_file),
        ];

        self.call_goto_instrument(args)
    }

    /// Apply annotated function contracts and loop contracts with goto-instrument.
    pub fn instrument_contracts(
        &self,
        harness: &HarnessMetadata,
        is_loop_contracts_enabled: bool,
        file: &Path,
    ) -> Result<()> {
        // Do nothing if neither loop contracts nor function contracts is enabled.
        if !is_loop_contracts_enabled && harness.contract.is_none() {
            return Ok(());
        }

        let mut dfcc_args: Vec<OsString> =
            vec!["--dfcc".into(), (&harness.mangled_name).into(), "--no-malloc-may-fail".into()];

        if is_loop_contracts_enabled {
            dfcc_args.append(&mut vec![
                "--apply-loop-contracts".into(),
                "--loop-contracts-no-unwind".into(),
                // Because loop contracts now are wrapped in a closure which will be a side-effect expression in CBMC even they
                // may not contain side-effect. So we disable the side-effect check for now and will implement a better check
                // instead of simply rejecting function calls and statement expressions.
                // See issue: diffblue/cbmc#8393
                "--disable-loop-contracts-side-effect-check".into(),
            ]);
        }

        let mut passes: Vec<Vec<OsString>> = vec![dfcc_args];
        if let Some(assigns) = harness.contract.as_ref() {
            let mut enforce_args: Vec<OsString> =
                vec!["--enforce-contract".into(), assigns.contracted_function_name.as_str().into()];

            if let Some(tracker) = &assigns.recursion_tracker {
                enforce_args.push("--nondet-static-exclude".into());
                enforce_args.push(tracker.as_str().into());
            }
            passes.push(enforce_args);
        }

        #[cfg(windows)]
        {
            // Work around goto-instrument crashes on Windows with long mangled artifact names.
            let short_file =
                file.with_file_name(format!("kani-instrument-{}.out", std::process::id()));
            fs::copy(file, &short_file).with_context(|| {
                format!(
                    "Failed to create temporary goto-instrument input {} from {}",
                    short_file.display(),
                    file.display()
                )
            })?;

            for mut pass_args in passes {
                pass_args.push(Self::normalize_tool_path(&short_file));
                pass_args.push(Self::normalize_tool_path(&short_file));

                if is_enforce_contract_pass(&pass_args) {
                    if let Err(err) =
                        self.call_goto_instrument_with_windows_fallback(&pass_args, &short_file)
                    {
                        let _ = fs::remove_file(&short_file);
                        return Err(err);
                    }
                } else if let Err(err) = self.call_goto_instrument_with_windows_timeout(
                    &pass_args,
                    goto_instrument_phase(&pass_args),
                ) {
                    if is_windows_goto_instrument_timeout(&err) {
                        if !self.args.common_args.quiet {
                            println!(
                                "Warning: Skipping {} on Windows after goto-instrument timeout",
                                goto_instrument_phase(&pass_args)
                            );
                        }
                        continue;
                    }
                    let _ = fs::remove_file(&short_file);
                    return Err(err);
                }
            }

            fs::copy(&short_file, file).with_context(|| {
                format!(
                    "Failed to copy temporary goto-instrument output {} to {}",
                    short_file.display(),
                    file.display()
                )
            })?;
            let _ = fs::remove_file(&short_file);
            Ok(())
        }

        #[cfg(not(windows))]
        {
            for mut pass_args in passes {
                pass_args.push(Self::normalize_tool_path(file));
                pass_args.push(Self::normalize_tool_path(file));
                self.call_goto_instrument(&pass_args)?;
            }
            Ok(())
        }
    }

    /// Generate a .demangled.c file from the .c file using the `prettyName`s from the symbol table
    ///
    /// Currently, only top-level function names and (most) type names are demangled.
    /// For local variables, it would be more complicated than a simple search and replace to obtain the demangled name.
    pub fn demangle_c(
        &self,
        pretty_name_map_file: &impl AsRef<Path>,
        c_file: &Path,
        demangled_file: &Path,
    ) -> Result<()> {
        let mut c_code = std::fs::read_to_string(c_file)?;
        let reader = BufReader::new(File::open(pretty_name_map_file)?);
        let value: serde_json::Value = serde_json::from_reader(reader)?;
        let pretty_name_map = value.as_object().unwrap();
        for (name, pretty_name) in pretty_name_map {
            if let Some(pretty_name) = pretty_name.as_str() {
                // Struct names start with "tag-", but this prefix is not used in the GotoC files, so we strip it.
                // If there is no such prefix, we leave the name unchanged.
                let name = name.strip_prefix("tag-").unwrap_or(name);
                if !pretty_name.is_empty() && pretty_name != name {
                    c_code = c_code.replace(name, pretty_name);
                }
            }
        }
        std::fs::write(demangled_file, c_code)?;
        Ok(())
    }

    /// Non-public helper function to actually do the run of goto-instrument
    fn call_goto_instrument<S: AsRef<OsStr>>(
        &self,
        args: impl IntoIterator<Item = S>,
    ) -> Result<()> {
        // TODO get goto-instrument path from self
        let mut cmd = Command::new("goto-instrument");
        cmd.args(args);

        self.run_suppress(cmd)
    }

    #[cfg(windows)]
    fn call_goto_instrument_with_windows_fallback(
        &self,
        args: &[OsString],
        file: &Path,
    ) -> Result<()> {
        let backup_file = file.with_extension("enforce-backup.out");
        fs::copy(file, &backup_file).with_context(|| {
            format!(
                "Failed to create backup goto model {} before --enforce-contract",
                backup_file.display()
            )
        })?;

        let result = (|| {
            if let Err(original_err) =
                self.call_goto_instrument_with_windows_timeout(args, "--enforce-contract")
            {
                let is_stack_overrun = is_windows_stack_buffer_overrun(&original_err);
                let is_timeout = is_windows_goto_instrument_timeout(&original_err);
                if !is_stack_overrun && !is_timeout {
                    return Err(original_err);
                }

                let Some(requested_contract) = enforce_contract_target(args) else {
                    return Err(original_err);
                };

                if is_timeout {
                    fs::copy(&backup_file, file).with_context(|| {
                        format!(
                            "Failed to restore goto model {} from backup {}",
                            file.display(),
                            backup_file.display()
                        )
                    })?;
                    if !self.args.common_args.quiet {
                        println!(
                            "Warning: Skipping --enforce-contract for {} on Windows after goto-instrument timeout",
                            requested_contract
                        );
                    }
                    return Ok(());
                }

                let candidates =
                    self.find_alternative_contract_symbols(&backup_file, requested_contract)?;
                for candidate in candidates {
                    fs::copy(&backup_file, file).with_context(|| {
                        format!(
                            "Failed to restore goto model {} from backup {}",
                            file.display(),
                            backup_file.display()
                        )
                    })?;

                    let mut retry_args = args.to_vec();
                    retry_args[1] = candidate.clone().into();
                    match self.call_goto_instrument_with_windows_timeout(
                        &retry_args,
                        "--enforce-contract",
                    ) {
                        Ok(()) => {
                            if !self.args.common_args.quiet {
                                println!(
                                    "Warning: Retried --enforce-contract with fallback symbol `{}` after Windows goto-instrument crash for `{}`",
                                    candidate, requested_contract
                                );
                            }
                            return Ok(());
                        }
                        Err(retry_err)
                            if is_windows_stack_buffer_overrun(&retry_err)
                                || is_windows_goto_instrument_timeout(&retry_err) =>
                        {
                            continue;
                        }
                        Err(retry_err) => return Err(retry_err),
                    }
                }
                fs::copy(&backup_file, file).with_context(|| {
                    format!(
                        "Failed to restore goto model {} from backup {}",
                        file.display(),
                        backup_file.display()
                    )
                })?;
                if !self.args.common_args.quiet {
                    println!(
                        "Warning: Skipping --enforce-contract for {} on Windows after goto-instrument crashes",
                        requested_contract
                    );
                }
                Ok(())
            } else {
                Ok(())
            }
        })();

        let _ = fs::remove_file(&backup_file);
        result
    }

    #[cfg(windows)]
    fn call_goto_instrument_with_windows_timeout(
        &self,
        args: &[OsString],
        phase: &str,
    ) -> Result<()> {
        let timeout_secs = std::env::var("KANI_WINDOWS_GOTO_INSTRUMENT_TIMEOUT_SECS")
            .ok()
            .and_then(|v| v.parse::<u64>().ok())
            .unwrap_or(300);
        let timeout = Duration::from_secs(timeout_secs);
        let trace_timeout = std::env::var("KANI_WINDOWS_GOTO_INSTRUMENT_TRACE")
            .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
            .unwrap_or(false);

        let mut cmd = Command::new("goto-instrument");
        cmd.args(args);
        if trace_timeout {
            let rendered_args =
                args.iter().map(|arg| arg.to_string_lossy()).collect::<Vec<_>>().join(" ");
            eprintln!(
                "[kani/windows-timeout] starting phase={phase} timeout_secs={timeout_secs} args={rendered_args}"
            );
        }
        if self.args.common_args.quiet {
            cmd.stdout(std::process::Stdio::null());
            cmd.stderr(std::process::Stdio::null());
        }

        let mut child = cmd.spawn().with_context(|| {
            format!("Failed to invoke goto-instrument ({}) with timeout {}s", phase, timeout_secs)
        })?;
        let start = Instant::now();

        loop {
            if let Some(status) = child.try_wait()? {
                if !status.success() {
                    anyhow::bail!("goto-instrument exited with status {}", status);
                }
                return Ok(());
            }

            if start.elapsed() >= timeout {
                if trace_timeout {
                    eprintln!(
                        "[kani/windows-timeout] timeout phase={phase} elapsed_secs={} killing goto-instrument",
                        start.elapsed().as_secs()
                    );
                }
                let _ = child.kill();
                let _ = child.wait();
                anyhow::bail!("goto-instrument ({phase}) timed out after {} seconds", timeout_secs);
            }

            std::thread::sleep(Duration::from_millis(200));
        }
    }
    #[cfg(windows)]
    fn find_alternative_contract_symbols(
        &self,
        file: &Path,
        requested_contract: &str,
    ) -> Result<Vec<String>> {
        let Some(contract_anchor) = contract_anchor(requested_contract) else { return Ok(vec![]) };
        let mut cmd = Command::new("goto-instrument");
        cmd.arg("--show-symbol-table").arg(Self::normalize_tool_path(file));
        let output =
            cmd.output().context("Failed to invoke goto-instrument for symbol table fallback")?;
        if !output.status.success() {
            return Ok(vec![]);
        }

        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);
        let text = format!("{stdout}\n{stderr}");
        let mut candidates = Vec::new();
        for line in text.lines() {
            let Some(symbol) = line.trim().strip_prefix("Symbol......: ") else { continue };
            if symbol.contains("::") {
                continue;
            }
            if symbol == requested_contract {
                continue;
            }
            if symbol.starts_with("_RNC") && symbol.contains(&contract_anchor) {
                candidates.push(symbol.to_string());
            }
        }

        let preferred_shape = preferred_contract_shape(requested_contract);

        // Prefer candidates that match the requested symbol shape and avoid nested closure symbols.
        candidates.sort_by_key(|name| {
            let same_shape_rank =
                if preferred_shape.is_some_and(|shape| name.contains(shape)) { 0 } else { 1 };

            let shape_rank = if name.contains("Es0_") {
                0
            } else if name.contains("Es1_") {
                1
            } else if name.contains("Es_") {
                2
            } else if name.contains("E0") {
                3
            } else {
                4
            };
            let nested_penalty = if name.contains("RNCNC") { 10 } else { 0 };
            same_shape_rank * 100 + shape_rank + nested_penalty
        });
        candidates.dedup();
        Ok(candidates)
    }
}

fn goto_instrument_phase(args: &[OsString]) -> &str {
    args.first().and_then(|arg| arg.to_str()).unwrap_or("<unknown-pass>")
}
fn is_enforce_contract_pass(args: &[OsString]) -> bool {
    matches!(args.first().and_then(|arg| arg.to_str()), Some("--enforce-contract"))
}

fn enforce_contract_target(args: &[OsString]) -> Option<&str> {
    args.get(1).and_then(|arg| arg.to_str())
}

fn contract_anchor(contract: &str) -> Option<String> {
    let start = contract.find("contracts8")?;
    let tail = &contract[start..];
    let end = tail.find('E')?;
    Some(tail[..=end].to_string())
}

fn preferred_contract_shape(contract: &str) -> Option<&'static str> {
    ["Es0_", "Es1_", "Es_", "E0"].into_iter().find(|shape| contract.contains(shape))
}

fn is_windows_stack_buffer_overrun(err: &anyhow::Error) -> bool {
    let text = format!("{err:#}");
    let simple = err.to_string();
    text.contains("0xc0000409") || simple.contains("0xc0000409")
}

#[cfg(windows)]
fn is_windows_goto_instrument_timeout(err: &anyhow::Error) -> bool {
    let text = format!("{err:#}");
    let simple = err.to_string();
    text.contains("goto-instrument (") && text.contains("timed out after")
        || simple.contains("goto-instrument (") && simple.contains("timed out after")
}
